import type { ImageStyle, TextStyle, ViewStyle } from "react-native";

type Style = ViewStyle | TextStyle | ImageStyle;

const colors = {
  cream: "#fff8ee",
  ink: "#17120f",
  cocoa: "#6f3f2c",
  spark: "#f2542d",
  rain: "#356f95",
  white: "#ffffff",
  neutral600: "#525252",
  neutral200: "#e5e5e5",
  // GitHub-dark "OpenAI dev panel" palette for the DevPanel sidecar (issue #25).
  ghBg: "#0d1117",
  ghChip: "#1f2937",
  ghBorder: "#30363d",
  ghLow: "#7d8590",
  ghGood: "#3fb950",
  ghWarn: "#f0883e",
  ghBtn: "#238636",
  ghBtnAlt: "#2ea043",
};

const base: Record<string, Style> = {
  absolute: { position: "absolute" },
  "flex-1": { flex: 1 },
  "flex-row": { flexDirection: "row" },
  "items-center": { alignItems: "center" },
  "justify-center": { justifyContent: "center" },
  "justify-between": { justifyContent: "space-between" },
  "text-center": { textAlign: "center" },
  uppercase: { textTransform: "uppercase" },
  "font-semibold": { fontWeight: "600" },
  "font-bold": { fontWeight: "700" },
  "font-black": { fontWeight: "900" },
  "shadow-sm": {
    shadowColor: colors.ink,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
  },
  border: { borderWidth: 1 },
  "border-4": { borderWidth: 4 },
  "border-neutral-200": { borderColor: colors.neutral200 },
  "border-cocoa": { borderColor: colors.cocoa },
  "bg-cream": { backgroundColor: colors.cream },
  "bg-cream/10": { backgroundColor: "rgba(255, 248, 238, 0.1)" },
  "bg-cream/20": { backgroundColor: "rgba(255, 248, 238, 0.2)" },
  "bg-ink": { backgroundColor: colors.ink },
  "bg-cocoa": { backgroundColor: colors.cocoa },
  "bg-rain": { backgroundColor: colors.rain },
  "bg-spark": { backgroundColor: colors.spark },
  "bg-white": { backgroundColor: colors.white },
  "bg-white/10": { backgroundColor: "rgba(255, 255, 255, 0.1)" },
  "bg-white/15": { backgroundColor: "rgba(255, 255, 255, 0.15)" },
  "bg-white/20": { backgroundColor: "rgba(255, 255, 255, 0.2)" },
  "bg-white/40": { backgroundColor: "rgba(255, 255, 255, 0.4)" },
  "text-cream": { color: colors.cream },
  "text-cream/60": { color: "rgba(255, 248, 238, 0.6)" },
  "text-cream/70": { color: "rgba(255, 248, 238, 0.7)" },
  "text-cream/80": { color: "rgba(255, 248, 238, 0.8)" },
  "text-ink": { color: colors.ink },
  "text-cocoa": { color: colors.cocoa },
  "text-rain": { color: colors.rain },
  "text-spark": { color: colors.spark },
  "text-white": { color: colors.white },
  "text-white/30": { color: "rgba(255, 255, 255, 0.3)" },
  "text-white/40": { color: "rgba(255, 255, 255, 0.4)" },
  "text-white/50": { color: "rgba(255, 255, 255, 0.5)" },
  "text-white/60": { color: "rgba(255, 255, 255, 0.6)" },
  "text-white/70": { color: "rgba(255, 255, 255, 0.7)" },
  "text-white/80": { color: "rgba(255, 255, 255, 0.8)" },
  "text-neutral-600": { color: colors.neutral600 },
  "text-xs": { fontSize: 12 },
  "text-sm": { fontSize: 14 },
  "text-base": { fontSize: 16 },
  "text-2xl": { fontSize: 24 },
  "text-3xl": { fontSize: 30 },
  "text-4xl": { fontSize: 36 },
  "text-5xl": { fontSize: 48 },
  "text-6xl": { fontSize: 60 },
  "text-[11px]": { fontSize: 11 },
  "text-[40px]": { fontSize: 40 },
  "text-[96px]": { fontSize: 96 },
  "font-thin": { fontWeight: "100" },
  "font-extralight": { fontWeight: "200" },
  "font-light": { fontWeight: "300" },
  "leading-5": { lineHeight: 20 },
  "leading-6": { lineHeight: 24 },
  "leading-9": { lineHeight: 36 },
  "leading-[44px]": { lineHeight: 44 },
  "tracking-[1px]": { letterSpacing: 1 },
  "tracking-[2px]": { letterSpacing: 2 },
  "tracking-[3px]": { letterSpacing: 3 },
  "rounded-full": { borderRadius: 999 },
  "rounded-2xl": { borderRadius: 16 },
  "rounded-3xl": { borderRadius: 24 },
  "rounded-[22px]": { borderRadius: 22 },
  "rounded-[32px]": { borderRadius: 32 },
  "rounded-[34px]": { borderRadius: 34 },
  "rounded-t-[34px]": { borderTopLeftRadius: 34, borderTopRightRadius: 34 },
  "h-1": { height: 4 },
  "w-1": { width: 4 },
  "h-2": { height: 8 },
  "w-2": { width: 8 },
  "h-32": { height: 128 },
  "w-32": { width: 128 },
  "h-36": { height: 144 },
  "w-36": { width: 144 },
  "h-44": { height: 176 },
  "h-72": { height: 288 },
  "w-72": { width: 288 },
  "w-full": { width: "100%" },
  "gap-1": { gap: 4 },
  "gap-2": { gap: 8 },
  "gap-3": { gap: 12 },
  "gap-4": { gap: 16 },
  "p-4": { padding: 16 },
  "p-5": { padding: 20 },
  "p-6": { padding: 24 },
  "px-2": { paddingHorizontal: 8 },
  "px-3": { paddingHorizontal: 12 },
  "px-4": { paddingHorizontal: 16 },
  "px-5": { paddingHorizontal: 20 },
  "py-2": { paddingVertical: 8 },
  "py-3": { paddingVertical: 12 },
  "py-4": { paddingVertical: 16 },
  "py-6": { paddingVertical: 24 },
  "mt-1": { marginTop: 4 },
  "mt-2": { marginTop: 8 },
  "mt-3": { marginTop: 12 },
  "mt-4": { marginTop: 16 },
  "mt-5": { marginTop: 20 },
  "mt-6": { marginTop: 24 },
  "mt-8": { marginTop: 32 },
  "mb-3": { marginBottom: 12 },
  "mb-4": { marginBottom: 16 },
  "mb-5": { marginBottom: 20 },
  "my-6": { marginVertical: 24 },
  "ml-2": { marginLeft: 8 },
  "ml-3": { marginLeft: 12 },
  "mr-2": { marginRight: 8 },
  "mr-3": { marginRight: 12 },
  "pl-3": { paddingLeft: 12 },
  "pl-4": { paddingLeft: 16 },
  "pr-2": { paddingRight: 8 },
  "pr-3": { paddingRight: 12 },
  "pr-4": { paddingRight: 16 },
  "py-2.5": { paddingVertical: 10 },
  "px-2.5": { paddingHorizontal: 10 },
  "h-9": { height: 36 },
  "w-9": { width: 36 },
  "h-10": { height: 40 },
  "w-10": { width: 40 },
  "self-center": { alignSelf: "center" },
  "self-start": { alignSelf: "flex-start" },
  "items-start": { alignItems: "flex-start" },
  "opacity-50": { opacity: 0.5 },
  "opacity-60": { opacity: 0.6 },
  "opacity-70": { opacity: 0.7 },
  "leading-4": { lineHeight: 16 },
  // ─── DevPanel sidecar (issue #25) — GitHub-dark "OpenAI dev panel" tokens ─
  "bg-gh-bg": { backgroundColor: colors.ghBg },
  "bg-gh-chip": { backgroundColor: colors.ghChip },
  "bg-gh-border": { backgroundColor: colors.ghBorder },
  "bg-gh-good": { backgroundColor: colors.ghGood },
  "bg-gh-warn": { backgroundColor: colors.ghWarn },
  "bg-gh-btn": { backgroundColor: colors.ghBtn },
  "bg-gh-btn-alt": { backgroundColor: colors.ghBtnAlt },
  "border-gh": { borderColor: colors.ghBorder },
  "border-l-gh": { borderLeftColor: colors.ghBorder, borderLeftWidth: 1 },
  "text-gh-low": { color: colors.ghLow },
  "text-gh-good": { color: colors.ghGood },
  "text-gh-warn": { color: colors.ghWarn },
  mono: { fontFamily: "Menlo" },
  "text-[10px]": { fontSize: 10 },
  "text-[13px]": { fontSize: 13 },
  "tracking-[0.5px]": { letterSpacing: 0.5 },
  "w-[260px]": { width: 260 },
  "h-[6px]": { height: 6 },
  "h-[4px]": { height: 4 },
  "rounded-md": { borderRadius: 6 },
  "rounded-sm": { borderRadius: 4 },
  "self-stretch": { alignSelf: "stretch" },
  "py-1": { paddingVertical: 4 },
  "py-1.5": { paddingVertical: 6 },
  "px-1": { paddingHorizontal: 4 },
  "px-1.5": { paddingHorizontal: 6 },
  "mb-1": { marginBottom: 4 },
  "mb-2": { marginBottom: 8 },
  "mt-0.5": { marginTop: 2 },
  "overflow-hidden": { overflow: "hidden" },
};

export function s(...classNames: Array<string | false | null | undefined>): Style[] {
  return classNames
    .filter(Boolean)
    .flatMap((className) => String(className).split(/\s+/))
    .map((token) => base[token])
    .filter(Boolean);
}
