"""Synthesize signal-context entries for OSM-hydrated merchants.

The canonical density fixture (`data/transactions/{city}-density.json`) only
covers a handful of hand-authored merchants per city (Berlin: 4 canonical;
Zurich: 0). The wallet drawer however lists ~35-40 OSM merchants per city
(see `momentmarkt_backend.merchants`). When `/demo/seed` runs, the LLM batch
pipeline asks `signals.build_signal_context(city, merchant_id)` for every
merchant. Without a density-fixture entry the call raises and the merchant
is skipped with `"no signal context"`.

This script generates a per-city `data/transactions/{city}-density-synthesized.json`
side-car with one entry per OSM merchant **not already in the canonical
fixture**. The shape is deliberately byte-identical to the canonical entries
so `signals.build_signal_context` does not need to branch.

Determinism: every per-merchant draw is seeded by `hash(merchant_id) % N`.
That keeps re-runs reproducible and ensures roughly half the merchants fire
the demand-gap trigger at 13:30 (the demo moment) while the other half do
not — gives the merchant inbox a believable "Vorgeschlagen" tab population.

CLI:
    python -m momentmarkt_backend.scripts.synthesize_signal_contexts berlin
    python -m momentmarkt_backend.scripts.synthesize_signal_contexts zurich
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timedelta
from math import asin, atan2, cos, degrees, radians, sin, sqrt
from pathlib import Path
from typing import Any

from ..fixtures import load_density
from ..merchants import search_merchants
from ..paths import DATA_DIR


# ---------------------------------------------------------------------------
# City-level constants (mirror what's authored in the canonical Berlin fixture).
# ---------------------------------------------------------------------------

CITY_META: dict[str, dict[str, Any]] = {
    "berlin": {
        "fixture_id": "berlin-mitte-payone-density-synth-v1",
        "city": "Berlin",
        "currency": "EUR",
        "currency_symbol": "€",
        "timezone": "Europe/Berlin",
        "tz_offset": "+02:00",
        "center_lat": 52.5301,
        "center_lon": 13.4012,
        "demo_context": {
            "day_of_week": "saturday",
            "demo_time_local": "2026-04-25T13:30:00+02:00",
            "mia_position": {
                "label": "Mia demo position near Rosenthaler Platz",
                "lat": 52.5301,
                "lon": 13.4012,
                "h3_cell_r8": "881f1d489dfffff",
            },
            "weather_trigger": "rain_incoming",
            "notes": (
                "Synthetic typical curves and live samples generated by "
                "synthesize_signal_contexts.py. Per-merchant noise is seeded "
                "by hash(merchant_id) so the gap pattern is reproducible."
            ),
        },
    },
    "zurich": {
        "fixture_id": "zurich-hb-payone-density-synth-v1",
        "city": "Zurich",
        "currency": "CHF",
        "currency_symbol": "CHF ",
        "timezone": "Europe/Zurich",
        "tz_offset": "+02:00",
        "center_lat": 47.3779,
        "center_lon": 8.5403,
        "demo_context": {
            "day_of_week": "saturday",
            "demo_time_local": "2026-04-25T13:30:00+02:00",
            "mia_position": {
                "label": "Mia demo position near Zurich HB",
                "lat": 47.3779,
                "lon": 8.5403,
                "h3_cell_r8": "881f8d4b29fffff",
            },
            "weather_trigger": "clear",
            "notes": (
                "Synthetic typical curves and live samples generated by "
                "synthesize_signal_contexts.py. Per-merchant noise is seeded "
                "by hash(merchant_id) so the gap pattern is reproducible."
            ),
        },
    },
}


DEMO_DATE = "2026-04-25"
DEMO_MOMENT_TIME = "13:30"


# ---------------------------------------------------------------------------
# Per-category typical-density templates (5x6 = 30-min granularity to match
# the canonical fixture: 12:00 → 14:30). Higher values = busier.
# ---------------------------------------------------------------------------
#
# Each template peaks at the times listed in the brief:
#   cafe → 08:00 + 14:00 (so by 13:30-14:30 the curve is high)
#   bakery → 06:30 + 12:00 (declining through the lunch window)
#   bar/pub → 18:00 + 22:00 (low at 13:30, rising)
#   restaurant → 12:30 + 19:30 (very high at lunch, dropping)
#   kiosk/eis/icecream → flatter, lift after 16:00 (modest at 13:30)
#   default → cafe template

CURVE_TIMES = ("12:00", "12:30", "13:00", "13:30", "14:00", "14:30")

CATEGORY_TEMPLATES: dict[str, dict[str, Any]] = {
    "cafe": {
        "densities": (54, 64, 74, 80, 78, 70),
        "txn_per_density": 0.22,
        "expires_minutes_after_demo": 60,
        "inventory_item": "afternoon_drip_coffee_and_pastries",
        "merchant_goal": "Fill the afternoon counter before the after-school lull.",
        "trigger_tags": ["saturday_lunch", "hot_drink", "nearby"],
        "rule_prefix": "cafe-afternoon",
        "surface_copy": "Frischer Filterkaffee, gleich um die Ecke.",
        "weather_extra_tags": ["rain_incoming"],
    },
    "bakery": {
        "densities": (60, 64, 56, 48, 38, 30),
        "txn_per_density": 0.32,
        "expires_minutes_after_demo": 75,
        "inventory_item": "sandwiches_and_pastries",
        "merchant_goal": "Move fresh sandwiches before the afternoon drop-off.",
        "trigger_tags": ["saturday_lunch", "bakery", "nearby"],
        "rule_prefix": "bakery-afternoon",
        "surface_copy": "Frische Stulle um die Ecke, bevor die Theke leer ist.",
        "weather_extra_tags": [],
    },
    "bar": {
        "densities": (18, 22, 26, 30, 34, 40),
        "txn_per_density": 0.28,
        "expires_minutes_after_demo": 90,
        "inventory_item": "house_apero_and_snacks",
        "merchant_goal": "Pull early apéro guests in before the evening rush.",
        "trigger_tags": ["weather_sensitive", "apero", "nearby"],
        "rule_prefix": "bar-early-apero",
        "surface_copy": "Apéro-Hour startet jetzt — Tisch frei.",
        "weather_extra_tags": ["rain_incoming"],
    },
    "restaurant": {
        "densities": (62, 78, 76, 70, 56, 44),
        "txn_per_density": 0.30,
        "expires_minutes_after_demo": 60,
        "inventory_item": "lunch_special_plate",
        "merchant_goal": "Convert the last lunch seats before the kitchen winds down.",
        "trigger_tags": ["saturday_lunch", "hot_meal", "nearby"],
        "rule_prefix": "resto-lunch-tail",
        "surface_copy": "Letzte Mittagstische — €3 Rabatt auf den Tagesteller.",
        "weather_extra_tags": ["rain_incoming"],
    },
    "kiosk": {
        "densities": (38, 40, 42, 44, 48, 52),
        "txn_per_density": 0.36,
        "expires_minutes_after_demo": 90,
        "inventory_item": "snack_and_drink_combo",
        "merchant_goal": "Move the drink-and-snack combo before the evening peak.",
        "trigger_tags": ["nearby", "snack"],
        "rule_prefix": "kiosk-afternoon",
        "surface_copy": "Snack + Getränk im Bundle — schnell mitnehmen.",
        "weather_extra_tags": [],
    },
    "ice_cream": {
        "densities": (40, 48, 56, 60, 64, 70),
        "txn_per_density": 0.26,
        "expires_minutes_after_demo": 75,
        "inventory_item": "two_scoop_cup",
        "merchant_goal": "Bring walk-ins for a scoop before the rain shifts foot traffic.",
        "trigger_tags": ["dessert", "weather_sensitive", "nearby"],
        "rule_prefix": "ice-afternoon",
        "surface_copy": "Noch ein Eis, bevor sich das Wetter dreht.",
        "weather_extra_tags": ["rain_incoming"],
    },
    "bookstore": {
        "densities": (32, 38, 44, 47, 55, 62),
        "txn_per_density": 0.16,
        "expires_minutes_after_demo": 90,
        "inventory_item": "paperback_table",
        "merchant_goal": "Bring nearby walkers indoors for low-friction browsing.",
        "trigger_tags": ["browse_indoor", "bookstore"],
        "rule_prefix": "bookstore-rain-browse",
        "surface_copy": "Regenpause mit einem neuen Taschenbuch.",
        "weather_extra_tags": ["rain_incoming"],
    },
    "boutique": {
        "densities": (30, 36, 44, 50, 56, 60),
        "txn_per_density": 0.14,
        "expires_minutes_after_demo": 90,
        "inventory_item": "seasonal_rack_browse",
        "merchant_goal": "Pull rainy-day browsers into the seasonal rack.",
        "trigger_tags": ["browse_indoor", "boutique"],
        "rule_prefix": "boutique-rain-browse",
        "surface_copy": "Trockene Anprobe statt Regenpause.",
        "weather_extra_tags": ["rain_incoming"],
    },
    "florist": {
        "densities": (28, 34, 38, 40, 42, 44),
        "txn_per_density": 0.18,
        "expires_minutes_after_demo": 75,
        "inventory_item": "saturday_bouquet",
        "merchant_goal": "Move Saturday bouquets before the close-of-day drop.",
        "trigger_tags": ["saturday_afternoon", "nearby"],
        "rule_prefix": "florist-afternoon",
        "surface_copy": "Saturday-Strauß zum Mitnehmen — frisch gebunden.",
        "weather_extra_tags": [],
    },
}


# Categories used in the brief that may not be in the catalog explicitly.
CATEGORY_ALIASES: dict[str, str] = {
    "pub": "bar",
    "eis": "ice_cream",
    "icecream": "ice_cream",
    "ice-cream": "ice_cream",
}


# Per-category offer-budget defaults (small per-merchant variance applied later).
CATEGORY_BUDGETS: dict[str, dict[str, float]] = {
    "cafe":       {"max_discount_percent": 15, "max_cashback_eur": 1.5, "total_budget_eur": 30.0},
    "bakery":     {"max_discount_percent": 10, "max_cashback_eur": 1.5, "total_budget_eur": 30.0},
    "bar":        {"max_discount_percent": 20, "max_cashback_eur": 2.0, "total_budget_eur": 40.0},
    "restaurant": {"max_discount_percent": 15, "max_cashback_eur": 2.5, "total_budget_eur": 45.0},
    "kiosk":      {"max_discount_percent": 12, "max_cashback_eur": 1.0, "total_budget_eur": 20.0},
    "ice_cream":  {"max_discount_percent": 15, "max_cashback_eur": 1.5, "total_budget_eur": 25.0},
    "bookstore":  {"max_discount_percent": 10, "max_cashback_eur": 2.0, "total_budget_eur": 30.0},
    "boutique":   {"max_discount_percent": 10, "max_cashback_eur": 2.0, "total_budget_eur": 35.0},
    "florist":    {"max_discount_percent": 12, "max_cashback_eur": 1.5, "total_budget_eur": 25.0},
}


# ---------------------------------------------------------------------------
# Determinism helpers.
# ---------------------------------------------------------------------------

def _seed(merchant_id: str, salt: str = "") -> int:
    """Return a deterministic non-negative int for `merchant_id` + optional salt.

    Python's built-in `hash()` is salted between processes (PYTHONHASHSEED),
    so we use a stable algorithm here. djb2-style is enough for our needs.
    """
    h = 5381
    for ch in (merchant_id + "::" + salt):
        h = ((h << 5) + h + ord(ch)) & 0xFFFFFFFF
    return h


def _seeded_pick(merchant_id: str, salt: str, lo: int, hi: int) -> int:
    """Deterministic int in [lo, hi] inclusive."""
    span = hi - lo + 1
    return lo + (_seed(merchant_id, salt) % span)


def _seeded_unit(merchant_id: str, salt: str) -> float:
    """Deterministic float in [0, 1)."""
    return (_seed(merchant_id, salt) % 10000) / 10000.0


# ---------------------------------------------------------------------------
# Geometry helpers.
# ---------------------------------------------------------------------------

def _haversine_m(lat1: float, lon1: float, lat2: float, lon2: float) -> int:
    earth_radius_m = 6_371_000
    phi1 = radians(lat1)
    phi2 = radians(lat2)
    d_phi = radians(lat2 - lat1)
    d_lambda = radians(lon2 - lon1)
    a = sin(d_phi / 2) ** 2 + cos(phi1) * cos(phi2) * sin(d_lambda / 2) ** 2
    return round(2 * earth_radius_m * asin(sqrt(a)))


def _project_lat_lon(
    center_lat: float,
    center_lon: float,
    distance_m: int,
    bearing_deg: float,
) -> tuple[float, float]:
    """Move `distance_m` from (center_lat, center_lon) along `bearing_deg`."""
    R = 6_371_000.0
    bearing = radians(bearing_deg)
    phi1 = radians(center_lat)
    lam1 = radians(center_lon)
    d_over_r = distance_m / R

    phi2 = asin(sin(phi1) * cos(d_over_r) + cos(phi1) * sin(d_over_r) * cos(bearing))
    lam2 = lam1 + atan2(
        sin(bearing) * sin(d_over_r) * cos(phi1),
        cos(d_over_r) - sin(phi1) * sin(phi2),
    )
    return round(degrees(phi2), 6), round(degrees(lam2), 6)


# ---------------------------------------------------------------------------
# Curve synthesis.
# ---------------------------------------------------------------------------

def _normalize_category(category: str) -> str:
    cat = category.strip().lower()
    cat = CATEGORY_ALIASES.get(cat, cat)
    if cat in CATEGORY_TEMPLATES:
        return cat
    return "cafe"  # default fallback per brief


def _typical_curve_points(category: str) -> list[dict[str, Any]]:
    template = CATEGORY_TEMPLATES[category]
    densities = template["densities"]
    txn_factor = template["txn_per_density"]
    return [
        {
            "time": time,
            "density": density,
            "expected_transactions": max(1, round(density * txn_factor)),
        }
        for time, density in zip(CURVE_TIMES, densities)
    ]


def _live_samples(
    merchant_id: str,
    category: str,
    typical_points: list[dict[str, Any]],
    tz_offset: str,
) -> list[dict[str, Any]]:
    """Perturb the typical curve at 13:00 / 13:15 / 13:30 / 13:45.

    The 13:30 perturbation is the one the demand-gap math reads. Per the
    brief, half the merchants fire the trigger and half don't — we drive
    the magnitude with a deterministic noise draw split into two regimes:

      - "drop" merchants (~half, by hash mod 2): live sits clearly below
        typical (gap_ratio comfortably above the 0.20 threshold).
      - "steady" merchants (~half): live is at-or-near typical, so the
        demand trigger does NOT fire (those will need other triggers like
        weather to fire — so they end up in the "Vorgeschlagen" inbox
        rather than an auto-approved offer).
    """
    typical_at_1330 = next(
        p["density"] for p in typical_points if p["time"] == DEMO_MOMENT_TIME
    )
    template = CATEGORY_TEMPLATES[category]
    txn_factor = template["txn_per_density"]

    is_drop = (_seed(merchant_id, "regime") % 2) == 0
    if is_drop:
        # Live sits 30-55% below typical at 13:30.
        drop_pct = 0.30 + (_seeded_unit(merchant_id, "drop_mag") * 0.25)
        live_at_1330 = max(0, round(typical_at_1330 * (1.0 - drop_pct)))
    else:
        # Within ±10% of typical → does not trigger demand gap.
        wobble = (_seeded_unit(merchant_id, "wobble") - 0.5) * 0.20
        live_at_1330 = max(0, round(typical_at_1330 * (1.0 + wobble)))

    # Bracket samples around the demo moment.
    typical_at = {p["time"]: p["density"] for p in typical_points}
    bracket = (("13:00", -0.05), ("13:15", -0.02), ("13:30", 0.0), ("13:45", 0.04))
    samples: list[dict[str, Any]] = []
    for time_key, drift in bracket:
        if time_key == "13:30":
            density = live_at_1330
        elif time_key == "13:00":
            base = typical_at.get("13:00", typical_at_1330)
            # Live at 13:00 sits between baseline and the eventual 13:30 live value
            # so the curve has shape and lands at the perturbed 13:30.
            blend = 0.6 if is_drop else 0.85
            density = max(0, round(base * blend + live_at_1330 * (1.0 - blend)))
        elif time_key == "13:15":
            base = (typical_at.get("13:00", typical_at_1330) + typical_at_1330) / 2
            blend = 0.4 if is_drop else 0.7
            density = max(0, round(base * blend + live_at_1330 * (1.0 - blend)))
        else:  # 13:45 (already past the gap moment)
            base = typical_at.get("14:00", typical_at_1330)
            blend = 0.4 if is_drop else 0.7
            density = max(0, round(base * (1.0 - blend) + live_at_1330 * blend))
            density = max(0, round(density * (1.0 + drift)))
        samples.append(
            {
                "time_local": f"{DEMO_DATE}T{time_key}:00{tz_offset}",
                "density": density,
                "observed_transactions": max(0, round(density * txn_factor)),
            }
        )
    return samples


def _demand_gap(
    typical_points: list[dict[str, Any]],
    live_samples: list[dict[str, Any]],
    tz_offset: str,
) -> dict[str, Any]:
    typical = next(
        p["density"] for p in typical_points if p["time"] == DEMO_MOMENT_TIME
    )
    live = next(
        s["density"] for s in live_samples if f"{DEMO_MOMENT_TIME}:00" in s["time_local"]
    )
    gap_points = typical - live
    gap_ratio = round(gap_points / typical, 2) if typical > 0 else 0.0
    threshold = 0.2
    if gap_points > 0:
        status = "below_typical"
    elif gap_points < 0:
        status = "above_typical"
    else:
        status = "at_typical"
    triggers = status == "below_typical" and gap_ratio >= threshold
    if triggers:
        reason = (
            f"Live density is {round(gap_ratio * 100)}% below the typical "
            f"{DEMO_MOMENT_TIME} baseline."
        )
    elif status == "below_typical":
        reason = (
            f"Live density is {round(gap_ratio * 100)}% below baseline — "
            "not enough to trigger a demand-gap offer."
        )
    elif status == "above_typical":
        reason = "Live traffic is at or above the typical Saturday baseline."
    else:
        reason = "Live density matches the typical baseline."
    return {
        "evaluated_at_local": f"{DEMO_DATE}T{DEMO_MOMENT_TIME}:00{tz_offset}",
        "typical_density": typical,
        "live_density": live,
        "gap_density_points": gap_points,
        "gap_ratio": gap_ratio,
        "threshold_ratio": threshold,
        "status": status,
        "triggers_demand_gap": triggers,
        "reason": reason,
    }


def _trigger_tags(
    category: str,
    weather_trigger: str,
    triggers_demand_gap: bool,
) -> list[str]:
    template = CATEGORY_TEMPLATES[category]
    tags = list(template["trigger_tags"])
    if weather_trigger == "rain_incoming" and "rain_incoming" in template["weather_extra_tags"]:
        if "rain_incoming" not in tags:
            tags.insert(0, "rain_incoming")
    if triggers_demand_gap and "demand_gap" not in tags:
        tags.append("demand_gap")
    return tags


def _autopilot_rule_hints(
    merchant_id: str,
    category: str,
    distance_m: int,
) -> dict[str, Any]:
    template = CATEGORY_TEMPLATES[category]
    # Roughly half auto-approved, half pending merchant review.
    approved = (_seed(merchant_id, "approval") % 2) == 0
    return {
        "approved": approved,
        "rule_id": f"{template['rule_prefix']}-{merchant_id[-5:]}",
        "conditions": [
            "demand_gap.gap_ratio>=0.20",
            f"distance_m<={max(250, distance_m + 100)}",
        ],
        "surface_copy_hint": template["surface_copy"],
    }


def _offer_budget(merchant_id: str, category: str) -> dict[str, Any]:
    base = CATEGORY_BUDGETS[category]
    # ±10% per-merchant variance on total budget; cashback wobbles ±0.5 EUR.
    variance = (_seeded_unit(merchant_id, "budget_var") - 0.5) * 0.20
    cashback_wobble = round((_seeded_unit(merchant_id, "cashback_var") - 0.5), 2)
    total = round(base["total_budget_eur"] * (1.0 + variance), 2)
    cashback = max(0.5, round(base["max_cashback_eur"] + cashback_wobble, 2))
    # Keep the canonical invariant: total >= 3 * cashback.
    if total < 3 * cashback:
        total = round(3 * cashback + 1, 2)
    return {
        "max_discount_percent": base["max_discount_percent"],
        "max_cashback_eur": cashback,
        "total_budget_eur": total,
    }


def _inventory_goal(
    merchant_id: str,
    category: str,
    tz_offset: str,
) -> dict[str, Any]:
    template = CATEGORY_TEMPLATES[category]
    base_minutes = template["expires_minutes_after_demo"]
    extra = _seeded_pick(merchant_id, "expiry", 0, 30)
    minutes = base_minutes + extra
    demo_dt = datetime.fromisoformat(f"{DEMO_DATE}T{DEMO_MOMENT_TIME}:00{tz_offset}")
    expires_dt = demo_dt + timedelta(minutes=minutes)
    target_redemptions = _seeded_pick(merchant_id, "target", 4, 12)
    return {
        "item": template["inventory_item"],
        "target_redemptions": target_redemptions,
        "expires_local": expires_dt.isoformat(timespec="seconds"),
    }


def _opening_hours(category: str) -> dict[str, str]:
    if category == "bakery":
        return {"saturday": "07:00-16:00"}
    if category == "bar":
        return {"saturday": "16:00-02:00"}
    if category == "restaurant":
        return {"saturday": "11:30-22:30"}
    if category == "ice_cream":
        return {"saturday": "11:00-20:00"}
    if category == "kiosk":
        return {"saturday": "07:00-22:00"}
    if category == "bookstore":
        return {"saturday": "10:00-19:00"}
    if category == "boutique":
        return {"saturday": "10:00-19:00"}
    if category == "florist":
        return {"saturday": "09:00-18:00"}
    # cafe + default
    return {"saturday": "08:00-18:00"}


# ---------------------------------------------------------------------------
# Main per-merchant synthesis.
# ---------------------------------------------------------------------------

def synthesize_one(
    catalog_entry: dict[str, Any],
    city_meta: dict[str, Any],
    weather_trigger: str,
) -> dict[str, Any]:
    merchant_id = catalog_entry["id"]
    category = _normalize_category(catalog_entry["category"])
    distance_m = int(catalog_entry["distance_m"])

    # Synthesize a plausible lat/lon from Mia's center + bearing seed.
    bearing = _seed(merchant_id, "bearing") % 360
    lat, lon = _project_lat_lon(
        city_meta["center_lat"], city_meta["center_lon"], distance_m, bearing
    )

    typical_points = _typical_curve_points(category)
    live_samples = _live_samples(merchant_id, category, typical_points, city_meta["tz_offset"])
    demand_gap = _demand_gap(typical_points, live_samples, city_meta["tz_offset"])
    trigger_tags = _trigger_tags(category, weather_trigger, demand_gap["triggers_demand_gap"])

    return {
        "id": merchant_id,
        "display_name": catalog_entry["display_name"],
        "category": category,
        "canonical_demo_merchant": False,
        "synthesized": True,
        "location": {
            "label": f"{catalog_entry['display_name']}, {catalog_entry.get('neighborhood', '')}".strip(", "),
            "lat": lat,
            "lon": lon,
        },
        "distance_m": distance_m,
        "currency": city_meta["currency"],
        "timezone": city_meta["timezone"],
        "opening_hours": _opening_hours(category),
        "demo_window": {
            "start_local": f"{DEMO_DATE}T12:00:00{city_meta['tz_offset']}",
            "end_local": f"{DEMO_DATE}T15:00:00{city_meta['tz_offset']}",
        },
        "typical_density_curve": {
            "day_of_week": "saturday",
            "time_zone": city_meta["timezone"],
            "points": typical_points,
        },
        "live_samples": live_samples,
        "demand_gap": demand_gap,
        "trigger_tags": trigger_tags,
        "merchant_goal": CATEGORY_TEMPLATES[category]["merchant_goal"],
        "inventory_goal": _inventory_goal(merchant_id, category, city_meta["tz_offset"]),
        "offer_budget": _offer_budget(merchant_id, category),
        "autopilot_rule_hints": _autopilot_rule_hints(merchant_id, category, distance_m),
    }


def _existing_canonical_ids(city: str) -> set[str]:
    """Ids already pinned in `<city>-density.json`.

    Returns an empty set if the city has no canonical fixture (Zurich today).
    """
    candidate = DATA_DIR / "transactions" / f"{city}-density.json"
    if not candidate.exists():
        return set()
    with candidate.open("r", encoding="utf-8") as f:
        data = json.load(f)
    return {m["id"] for m in data.get("merchants", [])}


def synthesize_city(city: str) -> dict[str, Any]:
    if city not in CITY_META:
        raise SystemExit(f"Unknown city: {city}. Known: {sorted(CITY_META)}")
    meta = CITY_META[city]
    catalog = search_merchants(city, query=None, limit=200) or []
    canonical_ids = _existing_canonical_ids(city)
    weather_trigger = meta["demo_context"]["weather_trigger"]

    synthesized: list[dict[str, Any]] = []
    for entry in catalog:
        if entry["id"] in canonical_ids:
            continue
        synthesized.append(synthesize_one(entry, meta, weather_trigger))

    return {
        "fixture_id": meta["fixture_id"],
        "description": (
            "Synthesized signal-context layer for OSM-hydrated merchants in "
            f"{meta['city']}. Generated by "
            "momentmarkt_backend.scripts.synthesize_signal_contexts."
        ),
        "city": meta["city"],
        "currency": meta["currency"],
        "timezone": meta["timezone"],
        "density_unit": "index_0_100",
        "sample_granularity_minutes": 15,
        "demo_context": meta["demo_context"],
        "merchants": synthesized,
    }


# ---------------------------------------------------------------------------
# CLI entry-point.
# ---------------------------------------------------------------------------

def _output_path(city: str) -> Path:
    return DATA_DIR / "transactions" / f"{city}-density-synthesized.json"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Synthesize per-merchant signal-context entries for OSM-hydrated "
            "catalogs (write `data/transactions/<city>-density-synthesized.json`)."
        ),
    )
    parser.add_argument("city", choices=sorted(CITY_META.keys()))
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Override output path (default: data/transactions/<city>-density-synthesized.json).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print summary without writing the file.",
    )
    args = parser.parse_args(argv)

    payload = synthesize_city(args.city)
    out_path = args.out or _output_path(args.city)

    fired = sum(
        1 for m in payload["merchants"] if m["demand_gap"]["triggers_demand_gap"]
    )
    auto = sum(1 for m in payload["merchants"] if m["autopilot_rule_hints"]["approved"])
    total = len(payload["merchants"])

    print(
        f"[synthesize_signal_contexts] city={args.city} synthesized={total} "
        f"demand_gap_fires={fired} ({(fired / total * 100) if total else 0:.0f}%) "
        f"autopilot_approved={auto}",
        file=sys.stderr,
    )

    if args.dry_run:
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"[synthesize_signal_contexts] wrote {out_path}", file=sys.stderr)
    # Touch load_density cache invalidation note (we don't actually clear it
    # — callers read from disk on next process start).
    _ = load_density  # silence unused-import warning if path lookup changes.
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
